### ISSUE TITLE
Liberapay account recipient isn't ready to receive new payments.

### ISSUE THREAD

**Issue by insanity54** [vladkens/twscrape#101]
Hi I'd like to set up a pledge via Liberapay, but I cannot. I see an error about the recipient account not being ready to receive new payments.

![Screenshot 2023-12-29 at 00-17-43 Giving - ~1583834 - Liberapay](https://github.com/vladkens/twscrape/assets/670375/76569509-a9d6-4ce7-89ee-97bb11046444)

**Comment by vladkens** [comment]
Hi, @insanity54. Thanks for writing about it. Fixed it.
