### ISSUE TITLE
Paypal is blocking donations

### ISSUE THREAD

**Issue by insanity54** [vladkens/twscrape#103]
Thanks for twscrape! I tried to make a pledge but Paypal won't let me proceed. This is the first time I've seen this error. 

> To comply with international regulations, this transaction has been declined.

![Screenshot 2023-12-31 at 14-01-28 PayPal](https://github.com/vladkens/twscrape/assets/670375/b9d3ede1-669f-463d-bda7-d2ea8ac6338c)

This is a big bummer as I'm using your code and I'd like to make a financial contribution.

To see if the issue was only with Liberapay, I tried donating via ko-fi instead. I got the same error via that website.

**Comment by vladkens** [comment]
Hi, @insanity54.

Thank you for this issue. I have never checked these services. Liberapay, ko-fi don't work for me so I removed them. Added [buymeacoffee](https://www.buymeacoffee.com/vladkens) instead, which looks to be working. Also posted a request on Github Sponsor, they should enable this feature for my profile later.

**Comment by vladkens** [comment]
@insanity54 thank you for your support!
