### ISSUE TITLE
Extracting Tweets with replies 

### ISSUE THREAD

**Issue by TharushaIQZ** [vladkens/twscrape#104]
Existing **user_tweets_and_replies** function extracts tweets and replies posted by a particular given user. However I want to extract all the replies of a particular tweet in my twitter profile. Is it possible using twscrape?

**Comment by vladkens** [comment]
Hi, @TharushaIQZ. This cannot be done in twscrape directly via a special handler, but can be done via search:

```py
async for tw in api.search("conversation_id:1637235385070678017 filter:replies"):
    print(tw)
```

or with CLI

```sh
twscrape search "conversation_id:1637235385070678017 filter:replies"
```

`conversation_id` is your tweet id. Not sure that `filter:replies` required.


_Note for me: twitter can load replies directly by `TweetDetail` operation with pagination ([example](https://twitter.com/elonmusk/status/1637235385070678017))_

**Comment by fernandoamorim30** [comment]
@TharushaIQZ, you was resolved your question? I`m have a similar issue.... I`m need get all replies from one tweet id in CSV or JSON or whatever....

**Comment by heyeanne34** [comment]
hello owner has this been added? pls add huhuhu , i want to get all comments and their nested replies in a tweet.. also do u have discord or any socmed where i can recommend more suggestions?

**Comment by vladkens** [comment]
Should be added in v0.11. If something wrong open new issue please.

**Comment by heyeanne34** [comment]
> Should be added in v0.11. If something wrong open new issue please.

can u pls teach to use huhuh
