### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lsl200032** [vladkens/twscrape#107]
2024-01-08 17:58:47.115 | ERROR    | twscrape.accounts_pool:login:148 - Failed to login to @lushilong172677: 
D:\anaconda\envs\crawl_twitter\Lib\site-packages\httpx\_client.py:1967: UserWarning: Unclosed <httpx.AsyncClient object at 0x0000023673E1B4D0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
how to slove this problem

**Comment by vladkens** [comment]
@lsl200032. Fixed, thank you!
