### ISSUE TITLE
Retrieve only tweets with media discarding retweets

### ISSUE THREAD

**Issue by lthrn** [vladkens/twscrape#108]
Is there a method to retrieve only tweets with embedded media which are also original tweets (not retweets).

I know how to filter out retweets from the result, but the issue is when an account has i.e 1000 original tweets with media but 100000 tweets/retweets in total. With the current approximate limit (3200), most of the results are tweets without media or retweets.

I was also thinking about pagination to get like 1000 tweets per page or something to "overcome" the limit and filter out all tweets, but I couldn't find any method or parameter to do this.

Is this even possible? I know the twitter web UI can do it when entering the media tab on each user profile page (twitter.com/USERNAME/media), but maybe the API cannot do that.

Thanks a lot!

**Comment by vladkens** [comment]
Hi, @lthrn. Media tab is something new in twitter. Need investigate API for this. At now you can use search api, like:

```py
api.search('from:@elonmusk filter:media')
```

More about search filters you can find here: https://github.com/igorbrigadir/twitter-advanced-search

**Comment by lthrn** [comment]
Hi,@vladkens. For now I'll try with the Search API like you suggested. Thanks a lot for your kind help.

**Comment by lthrn** [comment]
Hi again, @vladkens.

I tried using the Search API. Unfortunately the amount of tweets retrieved is even less than filtering out all tweet results. This may be because the API is getting only the "Top" tweets from the account.

I read the twitter advanced search link you suggested (thanks by the way), but I couldn't find any parameter o set of parameters to retrieve all tweets without the "Top" restriction.

Do you have any suggestion?

Thanks a lot again!

**Comment by Pigglebear** [comment]
#131

**Comment by vladkens** [comment]
@lthrn from [readme](https://github.com/vladkens/twscrape/blob/main/readme.md):

```
    # change search tab (product), can be: Top, Latest (default), Media
    await gather(api.search("elon musk", limit=20, kv={"product": "Top"}))
```

Default is Latest used.

**Comment by lthrn** [comment]
@vladkens Thanks a lot for the update.

I would like to know hot to pass the "Media" value using the CLI search command. I tried passing kv as argument but it says it's invalid: `unrecognized arguments: --kv={product: Media}`.

Thanks again.
