### ISSUE TITLE
IDs in Retrieve the Tweet Details

### ISSUE THREAD

**Issue by linxux** [vladkens/twscrape#116]
According to the [Twitter IDs](https://developer.twitter.com/en/docs/twitter-ids),
> Each object within Twitter - a Tweet, Direct Message, User, List, and so on - has a unique ID.

Twitter IDs are unique 64-bit unsigned integers that are generated by `Snowflake`.

The IDs in response from `api.tweet_details` should be represented as strings by default or with a conrecponse field suffix with `_str`,

- conversationId
- inReplyToTweetId
- inReplyToUser.id
- mentionedUsers[].id

```diff
{
  ...
  "conversationId":1751817528785936384,
+ "conversationId_str":"1751817528785936414",
  "inReplyToTweetId":1751817528785936384,
+ "inReplyToTweetId_str":"1751817528785936414",
  "inReplyToUser":{
    ...
    "id":1486473049146904576,
+   "id_str":"1486473049146904576"
  },
  "mentionedUsers":[
    {
...
      "id":1486473049146904576,
+     "id_str":"1486473049146904576"
    }
  ],
...
}
```

**Comment by vladkens** [comment]
@linxux should be fixed in v0.11.

Thank you!
