### ISSUE TITLE
Proxies support doesn't work properly

### ISSUE THREAD

**Issue by polyphia** [vladkens/twscrape#118]
There is something  wrong about the way proxies are handled and for some reason most of the times accounts with proxy fail to import with error 

`Failed to login to interrupted___4: Unknown scheme for proxy URL URL('%22http')`

The error is definitely not caused by the proxies themselves, or by the proxy format , as I have been able to add a couple of accounts that used the exact same proxy address and details as all the other ones failing, which leads me to think there is some other error that is not being handled properly when adding a proxy . 

The same issue has been reported by other users multiple times

**Comment by vladkens** [comment]
Hi, @polyphia.

Updated proxy support: https://github.com/vladkens/twscrape?tab=readme-ov-file#proxy
