### ISSUE TITLE
How to add terms in double quotes in the query for a search on exact phrase? (using Powershell on Windows)

### ISSUE THREAD

**Issue by seinecle** [vladkens/twscrape#120]
tried:

` "'Las Vegas' lang:en -is:retweet"
`
-> it works but Las and Vegas are not searched as an exact phrase

tried also:

```
 "`"Las Vegas`" lang:en -is:retweet -is:reply"
'"Las Vegas" lang:en -is:retweet -is:reply'
 """Las Vegas"" lang:en -is:retweet -is:reply"
```

And those three throw an error.

Any help is appreciated.

**Comment by vladkens** [comment]
Hi, @seinecle.

Just use it like:

```sh
twscrape search '"Las Vegas" lang:en -is:retweet -is:reply'
```

`"word"` used in X for exact text search.
`'` single quote to escape string in bash/powershell

Tested in PowerShell 7.4.0
