### ISSUE TITLE
Failed to login: AsyncClient.__init__() got an unexpected keyword argument 'proxy'

### ISSUE THREAD

**Issue by ywh03** [vladkens/twscrape#124]
upon running twscrape login_accounts I get this error; what could have caused it?

**Comment by vladkens** [comment]
Hi, @ywh03.

You need to update the version of the httpx dependency

Httpx version fixed in: https://github.com/vladkens/twscrape/releases/tag/v0.11.1

```
pip install --upgrade twscrape
```
