### ISSUE TITLE
Dependency: Internal error. (131)

### ISSUE THREAD

**Issue by 08jingles** [vladkens/twscrape#127]
`2024-02-20 14:05:34.187 | WARNING  | twscrape.queue_client:_check_rep:173 - Dependency error (request skipped): (131) Dependency: Internal error. (131)`

What can be done to resolve this error?

`twscrape: 0.11.1
SQLite client: 2.6.0
SQLite runtime: 3.37.2 (3.37.2)`

**Comment by malone6** [comment]
I have encountered the same error in `api.user_tweets_and_replies(175955419032031660, limit=1)`，but it returns correctly when I use [twitter-api-client](https://github.com/trevorhobenshield/twitter-api-client)
