### ISSUE TITLE
Login failed: login_username - 400, code 399, Infinite Loop

### ISSUE THREAD

**Issue by BFAGIT** [vladkens/twscrape#132]
Hello @vladkens, 
I've been playing around with your awesome library for a couple of months now. Thanks a lot for all the incredible work you have acheived.
I've been playing around in the last couple of days in the mass creation of twitter accounts I've found out the following edge case that I think  might be important to be managed in your library.

When Adding an account that does not exist and trying to login through-out either login_all() or relogin() the code gets locked in an infinite loop displaying the following warning:

`2024-02-28 10:36:05.154 | WARNING  | twscrape.utils:raise_for_status:39 - login_username - 400 - {"errors":[{"code":399,"message":"Sorry, we could not find your account."}]}`

Even though adding accounts that do not exist should be before hand checked by users I believe their might be some handling needed on the library side to avoid being stuck in a infinite loop and blocking all the rest of the execution.

The issue happens everytime with the relogin() method but only the first time with the login_all() method.

I'm running on the latest release v0.11.1 and python 3.11.2

Here is the following code used:
```py
import asyncio
from twscrape import API

async def main():
    api = API()
    await api.pool.add_account('Unexistingacounnt', 'Unexistingacounntpass', 'unexisting@unexistingemail.com','Unexistingacounntpass' )
    await api.pool.relogin('Unexistingacounnt')
await main()
```

Here is also a screenshot of the encountered issue:

![Screenshot 2024-02-28 at 10 36 22](https://github.com/vladkens/twscrape/assets/153183455/2dbf3ab2-0902-4f47-a681-f2d89943b777)

When calling accounts_info() i get the following infos for the account: 

```
{'active': False,
  'error_msg': "login_step=LoginEnterUserIdentifierSSO err=Client error '400",
  'last_used': None,
  'logged_in': False,
  'total_req': 0,
  'username': 'Unexistingacounnt'}
```
 I guess the error is correctly detected and raised but it is not handled correctly

Thanks a lot for all the hard work,
Kind regards,
BFAGIT

**Comment by ARKAD97** [comment]
Same issue.

I believe it is this loop:

https://github.com/vladkens/twscrape/blob/00a8e07b43c1fbbea95566cc3aae95db76cd4ae3/twscrape/login.py#L226-L235

**Comment by vladkens** [comment]
Planned to release in v0.12. Thank you for catching this!
