### ISSUE TITLE
Response status when Accounts is banned or session Expired

### ISSUE THREAD

**Issue by 0xGhostCasper** [vladkens/twscrape#142]
Hi, @vladkens !

I thought it would be super useful to return some kind of Command or Query result objects from method calls with success status codes and error reasons instead of just returning None values in case of expired session or banned account, because right now we cannot spot and react to situations when account gets banned or session expires - we only see debug logs and that's it, this is not helping to manage application flow.

I believe this should be useful for others aswell, I believe I already saw such suggestion before here in issues section.

**Comment by sicholas** [comment]
#137 This is what was causing my scripts to never grab full following. Would hit a banned account and would just stop the gather function.
