### ISSUE TITLE
2024-03-14 12:07:46.795 | ERROR    | twscrape.accounts_pool:login:148 - Failed to login to @XAccount: 'ct0'

### ISSUE THREAD

**Issue by LorenzEh** [vladkens/twscrape#143]
Can someone explain me what this error means?

2024-03-14 12:07:46.795 | ERROR    | twscrape.accounts_pool:login:148 - Failed to login to @XAccount: 'ct0'

thx

**Comment by jemather** [comment]
Getting the same erorr - ct0 is one of the authentication cookies for Twitter (https://help.twitter.com/en/rules-and-policies/x-cookies) along with auth_token and x-csrf-token. But haven't had time to figure out what's happening here yet.

**Comment by CrongCrong23** [comment]
were you guys able to find the solution? I'm currently facing the same issue :<

**Comment by jemather** [comment]
The issue went away for me in the interim, so my guess is its something on Twitter's end. If you can login to the account manually, you might try adding the account with a cookie.

**Comment by CrongCrong23** [comment]
I tried logging in today and the error was gone. Seems like you were right that the problem was on twitter's end.

**Comment by vladkens** [comment]
Most likely it is temporary IP ban, so `ct0` cookie not found.
Add check for this. Will be released in v0.12
