### ISSUE TITLE
[Feature request] Exit when no good account instead of waiting, for AWS Lambda

### ISSUE THREAD

**Issue by vsnig** [vladkens/twscrape#148]
I think we need an option to just exit when there's no good account. It's appropriate when running on AWS Lambda

P.S. now I'm thinking that probably the best option is to raise an Exception. This way we can use Lambda's native retry mechanism, or catch and ignore or react the way we wish

**Comment by vladkens** [comment]
Will be added in v0.12.

Usage:
```py
from twscrape import API, NoAccountError

api = API(raise_when_no_account=True)
try:
    api.search("foo", limit=10)
except NoAccountError:
    pass
```

Or with environment variable:
```sh
TWS_RAISE_WHEN_NO_ACCOUNT=1 twscrape tweet_details 1778577341163110904
```
