### ISSUE TITLE
It seems twilio user name, pwd, email and email pwd are sent to twscrape for login, is it safe?

### ISSUE THREAD

**Issue by midshipman** [vladkens/twscrape#149]

**Comment by vladkens** [comment]
Hi, @midshipman 

All data that you add to twscrape is stored locally on your computer in the accounts.db file. The data is used only for login to twitter.

Security depends on where (on which computer/server) you run twscrape.

An alternative way to login is to use accounts cookies - then you don't need to store your email/account passwords in a file.
