### ISSUE TITLE
get_user_by_id call sometimes fails

### ISSUE THREAD

**Issue by 0xGhostCasper** [vladkens/twscrape#15]
Hi again, @vladkens. After running lib for some time in test environment, I've observed that sometimes
I receive this error, when calling api.get_user_by_id(id):

```
File "/usr/local/lib/python3.11/site-packages/huntersdao/twitter_scraper/core.py", line 117, in get_user_by_id
    user = await self.api.user_by_id(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twscrape/api.py", line 107, in user_by_id
    res = rep.json()
          ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'
```

Could it be somehow related to the fact of accounts getting blocked or restricted
temporarily?

**Comment by vladkens** [comment]
Hi, @0xGhostCasper. I missed your issue. This means that content no more exist (deleted or hidden).

I will update api to return `None` in this case

**Comment by vladkens** [comment]
Hi, @0xGhostCasper. Added in `v0.7.0`

See changelog: https://github.com/vladkens/twscrape/releases/tag/v0.7.0
