### ISSUE TITLE
The search limit don't work and also the code return some tweets out of context ( not containing the keyword specified)

### ISSUE THREAD

**Issue by AbdellahAmini** [vladkens/twscrape#150]
i enter :
await gather(api.search(search_query, limit=10, kv={"product": "Latest"}))

but i still get a random number of tweets (more than 10) i want just the 10 latest in order

**Comment by atesahmet0** [comment]
I have the same problem

**Comment by vladkens** [comment]
Limit works in a specific way. Details here:
- https://github.com/vladkens/twscrape/issues/26#issuecomment-1627716826
- https://github.com/vladkens/twscrape/issues/84#issuecomment-1792359449

**Comment by AbdellahAmini** [comment]
I'm using the API to fetch the latest 10 tweets but frequently receive additional, irrelevant tweets or ads.
This inclusion distorts the context of my intended search results.

Could you suggest adjustments to the API call to solve this ?
