### ISSUE TITLE
Can it support login via auth_token only without cookies?

### ISSUE THREAD

**Issue by caterpillar1219** [vladkens/twscrape#152]
ref: https://github.com/HeavyHell/pytwex/tree/main/pytwex

**Comment by vladkens** [comment]
@caterpillar1219 

auth_token this is just one value of cookies.

https://github.com/HeavyHell/pytwex/blob/c3e5ccae9f3124a8a2c0d333b2cb6bd6fb2dad16/pytwex/client.py#L48

So just use cookies
