### ISSUE TITLE
Is there a way to remove an account added to the pool?

### ISSUE THREAD

**Issue by swetharamesh1998** [vladkens/twscrape#154]

**Comment by andylolz** [comment]
There is.

If you’re using the CLI, you can use:
```
$ twscrape del_accounts username
```

If you’re using the API, you can use:
```python
from twscrape import API

api = API()
await api.pool.delete_accounts("username")
```

**Comment by andylolz** [comment]
@swetharamesh1998 did this help? ^^

**Comment by swetharamesh1998** [comment]
Not really, I'm still getting an error 
Failed to login to @account : 'ct0'

**Comment by vladkens** [comment]
@swetharamesh1998 

From [readme](https://github.com/vladkens/twscrape/blob/main/readme.md)
```
twscrape del_accounts acc1 acc2
twscrape delete_inactive
```
