### ISSUE TITLE
What this KV?

### ISSUE THREAD

**Issue by sandersbasket** [vladkens/twscrape#16]
![image](https://github.com/vladkens/twscrape/assets/101429671/7c069239-db20-413d-9090-02905a16a009)
what is it and how to use it? I need page pagination (or cursor)

**Comment by vladkens** [comment]
Hi, @sandersbasket. kv is `variables` param form twitter GQL API.
Why it was added see in this topic: https://github.com/vladkens/twscrape/issues/4

What kind of cursor you need:
1) you want to start scrape from specific cursor
2) or you want to control all cursors
3) or you just need to receive cursor value?

**Comment by sandersbasket** [comment]
> Hi, @sandersbasket. kv is `variables` param form twitter GQL API. Why it was added see in this topic: #4
> 
> What kind of cursor you need:
> 
> 1. you want to start scrape from specific cursor
> 2. or you want to control all cursors
> 3. or you just need to receive cursor value?
when receiving a list of profile subscribers, I want to go immediately to the desired page (the last one I save, or something else) how do I implement this?

**Comment by vladkens** [comment]
It's hard to say. We need to study how the pagination token is formed and what kind of data is in it. I don't know the answer to that question. From the classic Twitter interface, you can only scroll down the page (get the next responses).

**Comment by sandersbasket** [comment]
> It's hard to say. We need to study how the pagination token is formed and what kind of data is in it. I don't know the answer to that question. From the classic Twitter interface, you can only scroll down the page (get the next responses).


but the use of the followers function is implemented through GraphQL, where the cursor is stored, it can simply be passed in the same way to the request (described in more detail here - https://github.com/vladkens/twscrape/issues/21)
![image](https://github.com/vladkens/twscrape/assets/101429671/9cb0851d-e323-48e8-a527-f68056781744)
just return the cursor of the last user and make it possible to pass it to the parameter - this is all that needs to be done, isn't it?

**Comment by sandersbasket** [comment]
@vladkens

**Comment by vladkens** [comment]
Hi, @sandersbasket.

Can you write code example of what do you want, to help me understand how you want use this feature. `twscrape` designed to work with different account same time (and share cursor between accounts), so it incapsulated in internal logic.

**Comment by sandersbasket** [comment]
@vladkens ok, give me u contacts telegram or add me (@sandersrocket)

**Comment by sandersbasket** [comment]
@vladkens ?
