### ISSUE TITLE
Twscrape is not grabbing all the responses

### ISSUE THREAD

**Issue by Tobiik** [vladkens/twscrape#161]
Hey, first of all, congratulations for this amazing project. However, it's currently impossible for me to get all the replies of a specific tweet because some of them are hidden due to two possible buttons:

![image](https://github.com/vladkens/twscrape/assets/12687381/a6de1c98-766d-43ab-a66f-4f7cdfb166a2)

![image](https://github.com/vladkens/twscrape/assets/12687381/7b3b45ee-3ede-4630-b9ff-f48943488db9)

is there a way to fix this? thanks!

**Comment by vladkens** [comment]
@Tobiik can you provide some example of such tweet / profile?
