### ISSUE TITLE
Question: No Active Account Issue

### ISSUE THREAD

**Issue by harisnaufal93** [vladkens/twscrape#167]
It seems that i recently cant perform scrapping with my account here, anyone knows the reason why?

![image](https://github.com/vladkens/twscrape/assets/114205745/cd69582d-4497-4d59-ab71-f194df08daf7)

**Comment by guntutur** [comment]
have you tried to delete accounts.db?

**Comment by vladkens** [comment]
Depends on how you added the account.

If it's through cookies, the account is probably banned.
If via login/password - you may have forgotten to make a login - `twscrape login_accounts`.

You can view the status of accounts with the command: `twscrape accounts`.

**Comment by deepblue6** [comment]
> have you tried to delete accounts.db?

Thank you this helped me 1 year later haha
