### ISSUE TITLE
How to get authenticated user info?

### ISSUE THREAD

**Issue by guntutur** [vladkens/twscrape#168]
i am using pool login for multiple account to get `user_tweets`

```
await api.pool.add_account("user1", "pass", "mail1@gmail.com", "")
await api.pool.add_account("user2", "pass", "mail2@ymail.com", "")
await api.pool.login_all()

async for tweet in api.user_tweets(target_id):

```

i just want to know from which logged in user (user1 or user2) the particular user tweet is acquired

**Comment by andylolz** [comment]
@guntutur You can if you use `api.user_tweets_raw`. So:

```python
from twscrape import API
from twscrape.models import parse_tweets

api = API()

await api.pool.add_account("user1", "pass", "mail1@gmail.com", "")
await api.pool.add_account("user2", "pass", "mail2@ymail.com", "")
await api.pool.login_all()

async for rep in api.user_tweets_raw(target_id):
    print(rep.__username)  # either user1 or user2
    for x in parse_tweets(rep.json(), limit):
        ...
```

**Comment by guntutur** [comment]
> @guntutur You can if you use `api.user_tweets_raw`. So:
> 
> ```python
> from twscrape import API
> from twscrape.models import parse_tweets
> 
> api = API()
> 
> await api.pool.add_account("user1", "pass", "mail1@gmail.com", "")
> await api.pool.add_account("user2", "pass", "mail2@ymail.com", "")
> await api.pool.login_all()
> 
> async for rep in api.user_tweets_raw(target_id):
>     print(rep.__username)  # either user1 or user2
>     for tweet in parse_tweets(rep.json()):
>         ...
> ```

Thanks andy, will try, is there any particular reason why `__username` ref only available in `user_teeets_raw` method?

**Comment by andylolz** [comment]
@guntutur Good question. I don’t know the answer I’m afraid.

It’s possible it’s just set for debugging purposes, and later discarded.

It’s set just here:
https://github.com/vladkens/twscrape/blob/00a8e07b43c1fbbea95566cc3aae95db76cd4ae3/twscrape/queue_client.py#L209

then it’s discarded when `rep.json()` is called:
https://github.com/vladkens/twscrape/blob/00a8e07b43c1fbbea95566cc3aae95db76cd4ae3/twscrape/api.py#L327

**Comment by vladkens** [comment]
Hi. The design of twscape was such that it doesn't delve into what specific account is currently being used. So this information is obviously not available anywhere.

But for any _raw method, you can read the field: `__username`:
```py
import asyncio

from twscrape import API, gather
from twscrape.models import parse_tweets


async def main():
    api = API()
    async for rep in api.search_raw("python", limit=10):
        print("Account used:", getattr(rep, "__username", None))
        for doc in parse_tweets(rep):
            print(doc.url)


if __name__ == "__main__":
    asyncio.run(main())

```
