### ISSUE TITLE
twitter ask for a number now 

### ISSUE THREAD

**Issue by raquelvalentina** [vladkens/twscrape#183]
I don't know if other people are experiencing this issue, but I have provided all the requirements to the API in the accounts.txt file, and I still receive an error. I don't know if it's because Twitter now requires a username, password, and a phone number. If I am using the API incorrectly, please let me know. I have tried with different accounts and encountered the same problem.

![descarga](https://github.com/vladkens/twscrape/assets/66224544/cfb1032f-76b3-4658-8a32-936ddd5f436c)

**Comment by raquelvalentina** [comment]
Well, I tested this locally, and I didn't encounter any problems, so everything seems to be working fine. Sorry for any confusion.

**Comment by vladkens** [comment]
@raquelvalentina your welcome 🙃
