### ISSUE TITLE
Add parameter cursor in functions 

### ISSUE THREAD

**Issue by sandersbasket** [vladkens/twscrape#21]
I saw that there is a function to get the cursor:

```python
    def _get_cursor(self, obj: dict):
        if cur := find_obj(obj, lambda x: x.get("cursorType") == "Bottom"):
            return cur.get("value")
        return None

```
but I also noticed that even if you get the cursor - pass it to the function through a parameter - it's impossible, only if you do it with the help of the _**_gql_items**_ function, but I would like to see an implementation method in this library - simpler
Is it possible to add a cursor to the parameter and return in the function (eg followers) - the last received cursor or just return the cursor to each user?

**Comment by vladkens** [comment]
Hi. Need to think about how this can be implemented.

Each api call function in API class have a second method ended with _raw. Those functions returns plain httpx.Response objects, so you can get last token yourself from it.

Not raw function was designed to get feed of parsed objects (tweets / users) for further processing.
