### ISSUE TITLE
Get user links when scraping profile

### ISSUE THREAD

**Issue by 0xGhostCasper** [vladkens/twscrape#23]
Hi @vladkens, would it be possible to scrape twitter user profile links, if present?
Right now I can't see this data in returned User type. Or isn't it possible, since Twitter API
is not returning it?

**Comment by vladkens** [comment]
Hi, @0xGhostCasper.

User profile link should be in `.url` property. Same or tweet.

<img width="887" alt="image" src="https://github.com/vladkens/twscrape/assets/825754/df2a0a31-dd15-444b-9949-e072e0c893d7">

Or you need something else?

**Comment by 0xGhostCasper** [comment]
@vladkens I mean this one

![image](https://github.com/vladkens/twscrape/assets/125361508/c358c808-0484-4f5f-b891-3bfb099d6c1d)

**Comment by vladkens** [comment]
Hi, again @0xGhostCasper.

Added this in [v0.4.0](https://github.com/vladkens/twscrape/releases/tag/v0.4.0). Links from users profile stored in [`descriptionLinks`](https://github.com/vladkens/twscrape/blob/v0.4.0/twscrape/models.py#L110) field of user model. 

You can upgrade as:
```sh
pip install twscrape --upgrade
```
