### ISSUE TITLE
Login with cookie data

### ISSUE THREAD

**Issue by codilau** [vladkens/twscrape#24]
Hello, 
As others mentioned, most of the time the login flow detects automated logins and blocks twscrape. I tried various workarounds and the only way to manage logging in it other libraries is by using the ct0 and auth_token cookies. 
I tried adding a dict in tha accounts.db but still fails (403 Forbidden).
Is there any official way to use these cookies in twscrape?

for example:
    await pool.add_account(cookies={"ct0" : "...". "auth_token" : "..."})

Any help is well apreciated, thanks!

**Comment by pleblira** [comment]
hey @codilau, just wanted to say thanks for sharing about the existence of twscrape. It seems it will work for my small use case.  Odd that it was marked as off-topic on the original post on snscrape... go figure...

**Comment by ekalkanli** [comment]
@pleblira were you able to login to your account with twscrape? im getting an error when i try to login with the error message below

login_step=LoginAcid err=Email login error

**Comment by pleblira** [comment]
> @pleblira were you able to login to your account with twscrape? im getting an error when i try to login with the error message below
> 
> login_step=LoginAcid err=Email login error


Yes, I was able to log in and didn't run into the issue you described. The instructions on the repo page seem to have worked. 

```# twscrape add_accounts <file_path> <line_format>
# line_format should have "username", "password", "email", "email_password" tokens
# tokens delimeter should be same as an file
twscrape add_accounts accounts.txt username:password:email:email_password```

for password and email_password, I used the same password, my Twitter account password.

**Comment by ekalkanli** [comment]
@pleblira thanks for the reply mate. Were you using a Twitter Blue Checked(Verified) account while doing this?

**Comment by pleblira** [comment]
No, logging into a good old Twitter non-blue check twitter account that was never blue checked at any point.

**Comment by hockeybro12** [comment]
Hi @pleblira 

When trying to log in for user `twitter_user` with email `twitter_user_email@gmail.com`, I get the following output from the debugging system:

```
2023-07-04 19:37:49.915 | INFO     | twscrape.accounts_pool:login_all:117 - [1/1] Logging in twitter_user - twitter_user_email@gmal.com
2023-07-04 19:37:50.793 | ERROR    | twscrape.login:next_login_task:180 - Error in LoginSuccessSubtask: Client error '403 Forbidden' for url 'https://api.twitter.com/1.1/onboarding/task.json'
For more information check: https://httpstatuses.com/403
2023-07-04 19:37:50.793 | ERROR    | twscrape.login:login:206 - 403 error twitter_user - twitter_user_email@gmal.com
2023-07-04 19:37:50.794 | INFO     | twscrape.accounts_pool:login:103 - Logged in to twitter_user successfully
````

I do get an email at `twitter_user_email@gmail.com` that my account is logged in. However, `twscrape` doesn't save it.

When running `twscrape accounts`, I see:
```
───────────────────────────────────────────────────────────────────────────────────────────────────────────
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────
 ──────────────────────
username        logged_in  active  last_used  total_req  error_msg                                                                                                                                                                           
───────────────────────────────────────────────────────────────────────────────────────────────────────────
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────
 ──────────────────────
twitter_user  0          0       None       0          login_step=LoginSuccessSubtask err=Client error '403 Forbidden' for url 'https://api.twitter.com/1.1/onboarding/task.json'
For more information check: https://httpstatuses.com/403 
```

Any idea what could be wrong?

**Comment by hockeybro12** [comment]
> Hello, As others mentioned, most of the time the login flow detects automated logins and blocks twscrape. I tried various workarounds and the only way to manage logging in it other libraries is by using the ct0 and auth_token cookies. I tried adding a dict in tha accounts.db but still fails (403 Forbidden). Is there any official way to use these cookies in twscrape?
> 
> for example: await pool.add_account(cookies={"ct0" : "...". "auth_token" : "..."})
> 
> Any help is well apreciated, thanks!

@codilau What is the solution you used to add the ct0 and auth_token cookies to get around the 403? Can you give me an example? Thanks!

**Comment by ekalkanli** [comment]
@vladkens @variousred could be better people to tag

**Comment by codilau** [comment]
@hockeybro12 
I couldn't log in with only ct0 and auth_token inside the cookies field. After a successfull login, the .db gets populated with the headers {} too. My guess is, without populating that manually, "resuming" the session fails.
@vladkens could shed some light as I, too hope

**Comment by pleblira** [comment]
> Hi @pleblira
> 
> When trying to log in for user `twitter_user` with email `twitter_user_email@gmail.com`, I get the following output from the debugging system:
> 
> ```
> 2023-07-04 19:37:49.915 | INFO     | twscrape.accounts_pool:login_all:117 - [1/1] Logging in twitter_user - twitter_user_email@gmal.com
> 2023-07-04 19:37:50.793 | ERROR    | twscrape.login:next_login_task:180 - Error in LoginSuccessSubtask: Client error '403 Forbidden' for url 'https://api.twitter.com/1.1/onboarding/task.json'
> For more information check: https://httpstatuses.com/403
> 2023-07-04 19:37:50.793 | ERROR    | twscrape.login:login:206 - 403 error twitter_user - twitter_user_email@gmal.com
> 2023-07-04 19:37:50.794 | INFO     | twscrape.accounts_pool:login:103 - Logged in to twitter_user successfully
> ```
> 
> I do get an email at `twitter_user_email@gmail.com` that my account is logged in. However, `twscrape` doesn't save it.
> 
> When running `twscrape accounts`, I see:
> 
> ```
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────
>  ──────────────────────────────────────────────────────────────────────────────────────────────────────────
>  ──────────────────────
> username        logged_in  active  last_used  total_req  error_msg                                                                                                                                                                           
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────
>  ──────────────────────────────────────────────────────────────────────────────────────────────────────────
>  ──────────────────────
> twitter_user  0          0       None       0          login_step=LoginSuccessSubtask err=Client error '403 Forbidden' for url 'https://api.twitter.com/1.1/onboarding/task.json'
> For more information check: https://httpstatuses.com/403 
> ```
> 
> Any idea what could be wrong?

hey @hockeybro12, that's odd. I just tried again in a new venv, with a fresh new twitter account, and logging in works fine.

```
2023-07-05 08:13:16.228 | INFO     | twscrape.accounts_pool:login_all:117 - [1/1] Logging in <my_twitter_handle> - <my_twitter_email>@gmail.com
2023-07-05 08:13:17.383 | INFO     | twscrape.accounts_pool:login:103 - Logged in to <my_twitter_handle> successfully
```

I'm setting up the accounts.txt file in the same folder with the : separator, username:password:email:password, and the commands below are working fine.

```
twscrape add_accounts accounts.txt username:password:email:email_password
twscrape login_accounts
```

Did you try with a new twitter account? Maybe yours is flagged somehow?

**Comment by hockeybro12** [comment]
@pleblira  I just tried again with a new account, and yeah still have the same issue. Can you show me what your SQLITE database looks like? In the terminal just type `sqlite3 accounts.db` and then run `SELECT * FROM accounts;` and paste the output (you can anonymize it)? I can then just update my table to match that, then it may work.

@codilau How exactly did you change the DB? I tried messing with it but still can't get it to work to the point where I can run the search / tweet ID look up commands.

**Comment by codilau** [comment]
@hockeybro12 I edited the .db file with a sqlite3 editor. But, I couldn't get that to work neither, I just got lucky with the login working once and filling the table.

**Comment by hockeybro12** [comment]
@codilau How does your DB look now?

**Comment by pleblira** [comment]
> @pleblira I just tried again with a new account, and yeah still have the same issue. Can you show me what your SQLITE database looks like? In the terminal just type `sqlite3 accounts.db` and then run `SELECT * FROM accounts;` and paste the output (you can anonymize it)? I can then just update my table to match that, then it may work.
> 
> @codilau How exactly did you change the DB? I tried messing with it but still can't get it to work to the point where I can run the search / tweet ID look up commands.

Sure, here's the info!

```
<twitter_handle>|<twitter_password>|<my_email@gmail.com>|<my_password>|Mozilla/5.0 (Macintosh; U; PPC Mac OS X; da-dk) AppleWebKit/522+ (KHTML, like Gecko) Safari/419.3|1|{}|{"accept": "*/*", "accept-encoding": "gzip, deflate", "connection": "keep-alive", "user-agent": "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; da-dk) AppleWebKit/522+ (KHTML, like Gecko) Safari/419.3", "content-type": "application/json", "authorization": "Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA", "x-twitter-active-user": "yes", "x-twitter-client-language": "en", "x-guest-token": "1676567011395084288", "x-csrf-token": "c8cc0a4e520e263fedce030ff68b1e5d5cde9fac02c4efa24ecc3e16d1c6eaa1f7d18ff3a53be37f1d9d990e482aa82b1a9bd17f84e3d907977ba0d2435ee6ad92b55611a80b9e1e79d18bccacd8c7c7", "x-twitter-auth-type": "OAuth2Session"}|{"guest_id_marketing": "v1%3A168855969927537209", "guest_id_ads": "v1%3A168855969927537209", "personalization_id": "\"v1_qEGVqUiu1T3GJzsA2ZDkDg==\"", "guest_id": "v1%3A168855969927537209", "kdt": "EvVg4WRphIgAz7TlkwVC53UlsMi7Z81SYhLESCqV", "twid": "\"u=1676566132503789568\"", "ct0": "c8cc0a4e520e263fedce030ff68b1e5d5cde9fac02c4efa24ecc3e16d1c6eaa1f7d18ff3a53be37f1d9d990e482aa82b1a9bd17f84e3d907977ba0d2435ee6ad92b55611a80b9e1e79d18bccacd8c7c7", "auth_token": "05a36f95881896492d97ef3e15610691da954233", "att": "1-q78Suryc2zeJK5hwxal4GkgazrNJZdsdGowVkBer"}|||{}||
```

It's a burner Tw account so I'm not worried about missing redacting any personal info, but I'd appreciate it if you told me if I let something important through, just for learning.

**Comment by hockeybro12** [comment]
@pleblira Thanks, it works! I just used your headers and cookies and filled in my Twitter account details and now I can access the API. Thanks so much!

I don't think there's any personal info in there (just normal cookies and headers), but I'm not 100% sure about it either.

**Comment by variousred** [comment]
> > @pleblira I just tried again with a new account, and yeah still have the same issue. Can you show me what your SQLITE database looks like? In the terminal just type `sqlite3 accounts.db` and then run `SELECT * FROM accounts;` and paste the output (you can anonymize it)? I can then just update my table to match that, then it may work.
> > @codilau How exactly did you change the DB? I tried messing with it but still can't get it to work to the point where I can run the search / tweet ID look up commands.
> 
> Sure, here's the info!
> 
> ```
> <twitter_handle>|<twitter_password>|<my_email@gmail.com>|<my_password>|Mozilla/5.0 (Macintosh; U; PPC Mac OS X; da-dk) AppleWebKit/522+ (KHTML, like Gecko) Safari/419.3|1|{}|{"accept": "*/*", "accept-encoding": "gzip, deflate", "connection": "keep-alive", "user-agent": "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; da-dk) AppleWebKit/522+ (KHTML, like Gecko) Safari/419.3", "content-type": "application/json", "authorization": "Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA", "x-twitter-active-user": "yes", "x-twitter-client-language": "en", "x-guest-token": "1676567011395084288", "x-csrf-token": "c8cc0a4e520e263fedce030ff68b1e5d5cde9fac02c4efa24ecc3e16d1c6eaa1f7d18ff3a53be37f1d9d990e482aa82b1a9bd17f84e3d907977ba0d2435ee6ad92b55611a80b9e1e79d18bccacd8c7c7", "x-twitter-auth-type": "OAuth2Session"}|{"guest_id_marketing": "v1%3A168855969927537209", "guest_id_ads": "v1%3A168855969927537209", "personalization_id": "\"v1_qEGVqUiu1T3GJzsA2ZDkDg==\"", "guest_id": "v1%3A168855969927537209", "kdt": "EvVg4WRphIgAz7TlkwVC53UlsMi7Z81SYhLESCqV", "twid": "\"u=1676566132503789568\"", "ct0": "c8cc0a4e520e263fedce030ff68b1e5d5cde9fac02c4efa24ecc3e16d1c6eaa1f7d18ff3a53be37f1d9d990e482aa82b1a9bd17f84e3d907977ba0d2435ee6ad92b55611a80b9e1e79d18bccacd8c7c7", "auth_token": "05a36f95881896492d97ef3e15610691da954233", "att": "1-q78Suryc2zeJK5hwxal4GkgazrNJZdsdGowVkBer"}|||{}||
> ```
> 
> It's a burner Tw account so I'm not worried about missing redacting any personal info, but I'd appreciate it if you told me if I let something important through, just for learning.

probably just your `Bearer` token and `auth_token`

**Comment by pleblira** [comment]
> 
> probably just your `Bearer` token and `auth_token`

Thanks @variousred. My mistake... something I should be worried about? Is there a way to expire those if needed?

**Comment by variousred** [comment]
Not totally sure, you can change your password and see if those values have changed

**Comment by codilau** [comment]
@pleblira you can go to Security and account access -> apps and sessions and log-off that particular session to invalidate the cookies.

I would still keep to the subject of generally using cookie data programatically to login as stated in the first post.
for example:
**await pool.add_account(cookies={"ct0" : "...". "auth_token" : "..."})**
@vladkens i think it's not a bad ideea since Tw might play around with maybe mandatory 2FA ot other stuff to impede programatic access.

**Comment by vladkens** [comment]
Hi, @codilau and all who in thread. This issue relevant. I liked solution from first message, but this not enough to transfer account.

I need play a bit with api, to understand which other fields need to be populated (guest_token, something more?)

Probably it should be different method of adding account, because we need somehow to check that account working after token is transferred. Current flow with add account / login account may not work in this case.

**Comment by vladkens** [comment]
Adede in `v0.6.0`. Use `pip install --upgrade twscrape` to update.

See usage section: https://github.com/vladkens/twscrape#usage
