### ISSUE TITLE
Search endpoint changed

### ISSUE THREAD

**Issue by codilau** [vladkens/twscrape#25]
Hello,
Search now returns 404, watching other fellow scrapers, it seems that that endpoint got changed to the GraphQL version too.

**Comment by vladkens** [comment]
Hi, @codilau.

Thanks for issue. Endpoint updated in [v0.4.0](https://github.com/vladkens/twscrape/releases/tag/v0.4.0). User API not changed.

You can upgrade as:
```sh
pip install twscrape --upgrade
```
