### ISSUE TITLE
tweet.quotedTweet and tweet.retweetedTweet return None for quoted or retweeted Tweet

### ISSUE THREAD

**Issue by carlosdcuba1** [vladkens/twscrape#28]
The scraper user profile with replies Tweet model return None for tweet.quotedTweet and tweet.retweetedTweet. If the scraper is with raw function the value is inside json result.

**Comment by vladkens** [comment]
Hi, @carlosdcuba1. Can you provide tweet id as example, please?

**Comment by carlosdcuba1** [comment]
Here is a Tweet ID example:

@REDROJA4
1658409412799737856

**Comment by vladkens** [comment]
Hi, @carlosdcuba1.

Twitter updated theirs API responses. Parser updated, now it should work as expected.
Thank you for catch this.

Update to v0.5.0
```sh
pip install --upgrade twscrape
```
