### ISSUE TITLE
count limit in api.py/search_raw(self, q: str, limit=-1, kv=None) is not used

### ISSUE THREAD

**Issue by samisme24062000** [vladkens/twscrape#29]
count is always 20 `"count": 20`

**Comment by vladkens** [comment]
Hi, @samisme24062000.

I'm not sure I understand your question.
Limit is internal logic of lib, its not connected to twitter api.
Count is field in api call, you can see this issue for more details: https://github.com/vladkens/twscrape/issues/4

**Comment by samisme24062000** [comment]
Hello, @vladkens  , im using the api.search method , it always return 20 tweets, no matter what the limit set in arg, because the parameter is passed to function but not used in `def search_raw(self, q: str, limit=-1, kv=None)`, i had to change the `"count": 20` to` "count": limit`

**Comment by vladkens** [comment]
@samisme24062000 limit behaviour (for non raw methods) fixed in `v0.6.0`

count in twitter api in many methods ignored by twitter side.

to update use: `pip install --upgrade twscrape`
