### ISSUE TITLE
get_user call hangs when accounts.db already exists

### ISSUE THREAD

**Issue by 0xGhostCasper** [vladkens/twscrape#3]
Hello, I would like to thank for this wonderful library,

while testing it today, I've came to this case: when running code in the
first run get_user_by_id call works correctly and return user information, and as I see accounts.db
sqlite db is created.

However, when I try to run the code 2nd time I see no login is being made, so I assume account session from
accounts.db is being reused, however call to  get_user_by_id is never returned. 

When enabled DEBUG mode, I see this looping:

No accounts available for queue 'UserByRestId' (sleeping for 5 sec)

**Comment by vladkens** [comment]
@0xGhostCasper 

Hi. Most likely the cause is the same as in https://github.com/vladkens/twscrape/issues/7. I added a way to see accounts status through the [CLI](https://github.com/vladkens/twscrape#get-list-of-accounts-and-their-statuses).

Don't forget to update:
```sh
pip install twscrape --upgrade
```

**Comment by vladkens** [comment]
Old issue, closing it.
