### ISSUE TITLE
support for proxies?

### ISSUE THREAD

**Issue by ThallesP** [vladkens/twscrape#31]
is proxies supported?

**Comment by codilau** [comment]
I think it's one per account since the datatype is string instead of dict if i'm not mistaken.
You can add your proxy url in the database directly in it's dedicated field

**Comment by vladkens** [comment]
Hi, @ThallesP.

Currently proxies supported per account individually, so you can add specific proxy to specific account like:
```python
api.pool.add_account("user", "pass", "user@example.com", "email_pass", proxy="http://some-proxy.com:8080")
```

Tell me how you want to use it, it might make sense to add another mechanism for dealing with proxies.

**Comment by ThallesP** [comment]
> Hi, @ThallesP.
> 
> Currently proxies supported per account individually, so you can add specific proxy to specific account like:
> 
> ```python
> api.pool.add_account("user", "pass", "user@example.com", "email_pass", proxy="http://some-proxy.com:8080")
> ```
> 
> Tell me how you want to use it, it might make sense to add another mechanism for dealing with proxies.

Exactly what I want, per account, thanks!
Also, I would recommend to add a proxy usage as an example in the README.

**Comment by sazoo** [comment]
@vladkens  what would be the format for password protected proxies?

**Comment by codilau** [comment]
@sazoo This has nothing to do with the library, it's the usual **requests** implementation (you find plenty of examples online)
Also, your provider might have these examples.
**http://username:password@hostname:port**

**Comment by sazoo** [comment]
> @sazoo This has nothing to do with the library, it's the usual **requests** implementation (you find plenty of examples online) Also, your provider might have these examples. **http://username:password@hostname:port**

thanks!
