### ISSUE TITLE
Unable to fetch tweets 

### ISSUE THREAD

**Issue by reddere** [vladkens/twscrape#33]
It would be a good implementation to add an exception where you can catch whether or not you have been rate limited. I am not able to fetch tweets and I think the account I am using has been rate limited, but have no way to make sure it is the case.
 
Edit: actually I have not been rate limited but it is taking WAY longer to fetch tweets. why?

**Comment by vladkens** [comment]
Hi, @reddere.

twscape built to use with multiple accounts and hide their toggles. So exceptions is not an option. Also twitter has different limits on different endpoints, so it's hard to tell if an account is banned / rate limited in general or only at given endpoint.

There are logs, there is account information (`twscrape stats` OR `twscrape accounts` from cli). You can use it to understand the cause.

**Comment by reddere** [comment]
Thanks @vladkens. All I do is fetching tweets with `await gather(api.user_tweets())`

My intention was to catch that rate limit exception to move onto next account. 

Regardless, now I implemented that myself using the asyncio wait_for() method. It waits for 660 seconds (11 minutes) and if still its not able to complete `await gather(api.user_tweets())`, it will pass to the next account.
