### ISSUE TITLE
searching by date

### ISSUE THREAD

**Issue by sazoo** [vladkens/twscrape#35]
Is searching by date supported?
I am trying to search by date with this:
`search "elon since:2023-07-12_11:59:59_UTC until:2023-07-13_11:59:59_UTC`
but getting results as far back as 2021.

**Comment by vladkens** [comment]
@sazoo hi. you can check this repo for search params: https://github.com/igorbrigadir/twitter-advanced-search

Dates should work if you can it like:

```sh
twscrape search "elon since:2023-07-12_11:59:59_UTC until:2023-07-13_11:59:59_UTC"
```

or 

```python
api.search("elon since:2023-07-12_11:59:59_UTC until:2023-07-13_11:59:59_UTC")
```

If it not working this something bad on twitter side. But personally I never seen problem with dates.

**Comment by sazoo** [comment]
@vladkens yes, I think those returned outside the search dates are promoted content. Not 100% sure though
