### ISSUE TITLE
Login with only User & PW

### ISSUE THREAD

**Issue by Jxck-S** [vladkens/twscrape#36]
If 2FA is off on a Twitter account, can't we log in with just the username and password? If so can we have that method added?

**Comment by reddere** [comment]
need this one as well, as now with version 0.6.0 it's required to have all of them valid, while in 0.5.0 it was not. I downgraded to 0.5.0 just for this reason

**Comment by vladkens** [comment]
Hi there. I restore behaviour from `v0.5.0`, now possible again to pass login flow without email / email_password. Email check before login can be done with `email_first` param in login method or `--email-first` from cli.

See changelog: https://github.com/vladkens/twscrape/releases/tag/v0.7.0
