### ISSUE TITLE
get_sqlite_version() reports old version

### ISSUE THREAD

**Issue by codilau** [vladkens/twscrape#37]
Hello @vladkens ,
I have to comment out raising the SystemError on check_version() constantly because even though I have a compatible newer sqlite installation, this still triggers every time. Any ideea? On manually checking what version gets imported it's always the new one and also everything works as expected without any issues.

Is by posibility the function loading the system-wide install of sqlite3 instead of the one from the venv in which it is running?

Also, unrelated. Is a port to mysql (or option) on the to do list?

**Comment by vladkens** [comment]
Hi. Python comes with some sqlite version in the package and its very difficult to update its version.

If you are doing manual check from python program and version is different than twscrape shows then send example code please.

If you are checking the sqlite version in the system, it may be different. Python will not use it.

**Comment by codilau** [comment]
Fixed since 0.7.0
