### ISSUE TITLE
ability to increase get_user_following count to more than 20

### ISSUE THREAD

**Issue by 0xGhostCasper** [vladkens/twscrape#4]
Sorry for opening second isssue,

In source code I see this snippet:

` async def following_raw(self, uid: int, limit=-1):
        op = "IWP6Zt14sARO29lJT35bBw/Following"
        kv = {"userId": str(uid), "count": 20, "includePromotedContent": False}
        async for x in self._ql_items(op, kv, limit=limit):
            yield x`

Would it be possible to pass custom count number to that call or Twitter by itself hard limits calls to 20 per request?

**Comment by mutedcase** [comment]
@vladkens From a couple runs I just did from the raw graphql query in postman I changed count to 100 and 50 and i got 71 and 61 in response, respectively. sorta odd that it went over the count variable on the change to 50 though

**Comment by vladkens** [comment]
Hi, @0xGhostCasper & mutedcase.

I don't know why, but Twitter doesn't always return the same number of results.

Anyway, I've added the ability to change the parameters that are passed to GraphQL API.

The ones written in the code are the same ones twitter uses on its frontend. But now you can change it like this:

```typescript
# in kv you can pass any parameter used by twitter in gql api
api.following_raw(100, kv={'count': 100})
```
