### ISSUE TITLE
how tu use new!!

### ISSUE THREAD

**Issue by ihabpalamino** [vladkens/twscrape#44]
hello i want to get tweets by giving username of the account that i want to scrape plus start date since and end date until could u give me an example to do that please?

**Comment by ihabpalamino** [comment]
> Hi, @ihabpalamino.
> 
> ```python
> q = "from:@ElonMusk since:2020-01-01 until:2020-01-10"
> 
> async for t in api.search(q):
>     print(t.id, t.rawContent)
> ```
> 
> https://twitter.com/search?q=from%3A%40ElonMusk%20since%3A2020-01-01%20until%3A2020-01-10&src=typed_query&f=live
> 
> List of possible filters you can find here: https://github.com/igorbrigadir/twitter-advanced-search

can you provide more details about the code like imports and the login if its necessary...write the whole code

**Comment by vladkens** [comment]
Hi, @ihabpalamino.

Added few examples: https://github.com/vladkens/twscrape/tree/main/examples
