### ISSUE TITLE
Request for Multi-Processing Example

### ISSUE THREAD

**Issue by XWang20** [vladkens/twscrape#47]
Thank you for this amazing work! I've been using this project for a few days now, and it has been incredibly helpful in my work.

I'm currently working on a project where I need to search a large amount of keywords in parallel. However, I'm new to multi-processing and await function. I would like to see a simple example that I can build upon.

Could you please provide some examples that demonstrates how to use multi-processing to search a list of keywords in parallel?Thank you for your help!

**Comment by vladkens** [comment]
Hi, @XWang20.

Added few examples: https://github.com/vladkens/twscrape/tree/main/examples
