### ISSUE TITLE
Raise exception when no free accounts pool

### ISSUE THREAD

**Issue by NosikovSergey** [vladkens/twscrape#48]
Hello, I would like to thank you for your project.

I encountered an unexpected issue where the methods hang in an infinite loop when there are no accounts available until a free account becomes available. This is a significant problem for me, and I need to handle such situations.

Could you please consider adding a setting that would change this behavior?

The API creation could look like this:
`api = API(DB_PATH, raiseWhenNoAccount=True)`

And the function responsible for getting an account would be like this:

```
async def get_for_queue_or_raise(self, queue: str) -> Account:
    account = await self.get_for_queue(queue)
    if not account:
        nat = await self.next_available_at(queue)
        raise NoAvalibleAccountException(f'No account available for queue "{queue}". Next available at {nat}')
    return account
```

**Comment by vladkens** [comment]
Will be added in v0.12.

Usage:
```py
from twscrape import API, NoAccountError

api = API(raise_when_no_account=True)
try:
    api.search("foo", limit=10)
except NoAccountError:
    pass
```

Or with environment variable:
```sh
TWS_RAISE_WHEN_NO_ACCOUNT=1 twscrape tweet_details 1778577341163110904
```
