### ISSUE TITLE
Fetching Ads

### ISSUE THREAD

**Issue by reddere** [vladkens/twscrape#61]
Please implement a way to fetch ads from a username with `twscrape`.

Here is an example of ad from FortniteGame on twitter: https://twitter.com/FortniteGame/status/1696926119700709551

Also note that this ad does not come up when using `api.user_tweets()`

Thanks in advance @vladkens !

**Comment by vladkens** [comment]
Related to this: https://github.com/vladkens/twscrape/issues/72
