### ISSUE TITLE
Cannot insatll twscrape

### ISSUE THREAD

**Issue by LeoLCHuang** [vladkens/twscrape#63]
`pip install twscrape`  on the anaconda prompt and
`ERROR: Could not find a version that satisfies the requirement twscrape (from versions: none)`
`ERROR: No matching distribution found for twscrape` occurs,
also try `pip install git+https://github.com/vladkens/twscrape.git` and it still doesn't work,
how can i do to solve the problem?

**Comment by GunduzYuruyen** [comment]
I ve same problem

**Comment by AliSamhat07** [comment]
@LeoLCHuang @GunduzYuruyen Check your python version... Twscrape require python 3.10 or higher, according to [this acticle](https://medium.com/@vladkens/how-to-still-scrape-millions-of-tweets-in-2023-using-twscrape-97f5d3881434)
