### ISSUE TITLE
DB locked -> OperationalError

### ISSUE THREAD

**Issue by codilau** [vladkens/twscrape#64]
I'm running into this type of error while using multiple tasks. For some reason, my guess is, one task might be blocking another one from modifying the db and instead of waiting for the other task to release the resource, it raises this error.

**Comment by ernestng11** [comment]
Facing this issue too, queueclient does not switch from locked account to an available one in some cases. Any fixes for this?

**Comment by scvsh** [comment]
Facing database is locked when running many concurrent tweet fetching tasks. Here's my code

`async def fetch_user_tweets(api, acc_id):
    try:
        return await gather(api.user_tweets_and_replies(acc_id, limit=3200))
    except Exception as e:
        print(f"Error with user {acc_id}: {e}")
        return None

async def get_tweets(flws):
    flw_twts = []
    for i in range(1, len(flws)):
        print("Parsing followers...", i)
        tasks = [fetch_user_tweets(api, acc.id) for acc in flws[i]]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        flw_twts.extend([result for result in results if result is not None])
    return flw_twts`

Account pool is underutilized, also database locks seem to stack and completely prevent database from access

**Comment by scvsh** [comment]
Any idea if switching to postgres/mongo as a backend would help?
