### ISSUE TITLE
The current HTTPX requirement is not compatible with the requirement for python-telegram-bot

### ISSUE THREAD

**Issue by KostadinKrushkov** [vladkens/twscrape#65]
https://github.com/vladkens/twscrape/blob/745bc59b662b72e46b0f5277e369767f2b318c06/pyproject.toml#L23

The python-telegram-bot packages requires httpx-0.24.1 -> currently your project is at httpx-0.24.0
Can you bump it so the dependency is met. 

This is regarding python.3.10.5

You can check it out using:
pip install "python-telegram-bot[job-queue]"

ERROR: Cannot install -r requirements.txt (line 3) and -r requirements.txt (line 5) because these package versions have conflicting dependencies.
The conflict is caused by:
    twscrape 0.8.0 depends on httpx==0.24.0
    python-telegram-bot 20.5 depends on httpx~=0.24.1

**Comment by vladkens** [comment]
Hi. It was fixed in v0.9.0 https://github.com/vladkens/twscrape/blob/v0.9.0/pyproject.toml#L21
