### ISSUE TITLE
Including shortned tweet link

### ISSUE THREAD

**Issue by reddere** [vladkens/twscrape#68]
I think it would be useful to many (myself too) to include the shortened version of the tweet link in one of the params that get returned in a tweet object. 

This is useful especially when you need to remove the tweet link at the end of `rawContent`, but sometimes the author of the tweet puts a link at the end the tweet, and it happens that the final link at the end of `rawContent` is actually the link the author attached, and not the tweet URL.

**Comment by vladkens** [comment]
@reddere can you share tweet example?
