### ISSUE TITLE
No accounts available for queue 'UserTweetsAndReplies' 

### ISSUE THREAD

**Issue by Louvivien** [vladkens/twscrape#7]
Hello, 

Thanks for this code. 
When I use your template I get this debug message:

2023-05-27 14:19:12.137 | DEBUG    | twscrape.accounts_pool:get_for_queue_or_wait:129 - No accounts available for queue 'UserTweetsAndReplies' (sleeping for 5 sec)
2023-05-27 14:19:17.142 | DEBUG    | twscrape.accounts_pool:get_for_queue_or_wait:129 - No accounts available for queue 'UserTweetsAndReplies' (sleeping for 5 sec)
```

    await gather(api.search("elon musk", limit=1))  # list[Tweet]

    # graphql api
    tweet_id, user_id, user_login = 20, 2244994945, "twitterdev"

    await api.tweet_details(tweet_id)  # Tweet
    await gather(api.retweeters(tweet_id, limit=1))  # list[User]
    await gather(api.favoriters(tweet_id, limit=1))  # list[User]

    await api.user_by_id(user_id)  # User
    await api.user_by_login(user_login)  # User
    await gather(api.followers(user_id, limit=1))  # list[User]
    await gather(api.following(user_id, limit=1))  # list[User]
    await gather(api.user_tweets(user_id, limit=1))  # list[Tweet]
    await gather(api.user_tweets_and_replies(user_id, limit=1))  # list[Tweet]
```

What is wrong?

**Comment by vladkens** [comment]
Hi, @Louvivien. You should to add some accounts to pass the login flow (after that the session is saved and the accounts will be reused)

You can do this like:
```typescript
pool = AccountsPool()
await pool.add_account("user1", "pass1", "user1@example.com", "email_pass1")
await pool.add_account("user2", "pass2", "user2@example.com", "email_pass2")
```

And after this call login (not super fast process, because it synchronous):
```typescript
await pool.login_all()
```

After you can use search like:
```typescript
api = API(pool)
for tweet in api.search("elon musk", limit=1):
    print(tweet.id)
```

If you're still getting the message that there are no accounts available, it's probably a login error. This can be seen in the logs during login or if you look in the sqlite database.

In the next few days I will release an update with cli tool so you will be able to see the stats in the terminal

**Comment by Louvivien** [comment]
Yes i have added it but why do you need "user1", "pass1" and  "user1@example.com", "email_pass1" ? And for me pass1=email_pass1. 
I still get the error. Sometime I do not have it.

**Comment by vladkens** [comment]
Hi @Louvivien 

I added an ability to see accounts status through the [CLI](https://github.com/vladkens/twscrape#get-list-of-accounts-and-their-statuses).

Don't forget to update:
```sh
pip install twscrape --upgrade
```

I also added some explanation of why you need an email and password: https://github.com/vladkens/twscrape#usage

---

> sometime it would work after retries

I can't exactly identify the problem from your logs.

But most likely it is a limit on the number of requests. Twitter has a limit for each endpoint type to access the API over a period of time. You can see this one here: https://github.com/vladkens/twscrape#limitations

When the limit comes for an account, the program tries to take the next available account or wait until the limit is gone.

**Comment by vladkens** [comment]
Old issue, closing it.
