### ISSUE TITLE
[BUG] Not retrieving ad tweets correctly

### ISSUE THREAD

**Issue by reddere** [vladkens/twscrape#72]
Take this ad tweet as an example:

https://twitter.com/FortniteGame/status/1696922210588410217?t=2D0tOS0hkBt_PZUwPAbeGQ&s=19

`api.tweet_details(1696922210588410217)` only returns the text, in `rawContent`. No information about the video direct links, neither the  video title, which in this case is "Il colpo perfetto ha inizio!", nor the ad link (which in this case is https://fortnite.com/b/chapter4-season4?utm_source=Twitter&utm_campaign=FNBR_RT_C4S4_Twitter_LINK-CLICKS_IT).

**Comment by vladkens** [comment]
Will be added in v0.12.

Tweet now have .card field with .card._type = "poll" | "summary". When type is "summary", then all video info will be stored to .card

Model ref:
https://github.com/vladkens/twscrape/blob/24a51e12bdc2bde6f89018f01bd4fbfb3f09efb7/twscrape/models.py#L359
