### ISSUE TITLE
ApiError on 49/50 (Code 200) Authorization: Unauthorized

### ISSUE THREAD

**Issue by sicholas** [vladkens/twscrape#75]
|WARNING  | twscrape.queue_client:req:199 - Unknown error <class 'twscrape.queue_client.ApiError'>: ApiError on 49/50 - name (code 200): Authorization: unauthorized

I'm getting this error when trying to grab tweets.

**Comment by vladkens** [comment]
Hi. This is something from twitter side. Maybe fixed in this PR: https://github.com/vladkens/twscrape/pull/95

Closing this issue. If this error appear again please open new issue.
