### ISSUE TITLE
X's new Terms of Service 29th Sept 2023

### ISSUE THREAD

**Issue by PytechDevServices** [vladkens/twscrape#77]
According to a new update to the [Terms of Service](https://twitter.com/en/tos) that will also take effect on September 29, 2023, “crawling or scraping the Services in any form, for any purpose without our prior written consent is expressly prohibited.”

How will this affect using this library?

**Comment by vladkens** [comment]
Hi. Just don't do scraping =) Or ask Twitter for permission as it says in their rules.
