### ISSUE TITLE
twscrape.imap:_wait_email_code:53 - (149 of 149)

### ISSUE THREAD

**Issue by KingMaoDou** [vladkens/twscrape#86]
![image](https://github.com/vladkens/twscrape/assets/114294557/4df0817a-bdd4-411e-a03c-18227d959342)

**Comment by gniax** [comment]
same issue & even when the email with the verification code is received it keeps spamming the latest email content and never use the code, it is stuck.

**Comment by vladkens** [comment]
Hi, @KingMaoDou. Added ability yo enter verification code manually https://github.com/vladkens/twscrape?tab=readme-ov-file#enter-email-verification-code-manually
