### ISSUE TITLE
Unknown error <class 'twscrape.queue_client.ApiError'>: ApiError on 49/50 - *** (code 200): Dependency: Internal error. (131) ~ Dependency: Internal error. 

### ISSUE THREAD

**Issue by KingMaoDou** [vladkens/twscrape#89]
![image](https://github.com/vladkens/twscrape/assets/114294557/902d41ba-9471-4efb-ad25-6a20e28da11b)

At the beginning, I didn't encounter this problem until I scraped a certain amount of data.
I have tried the following solutions:
1. Use a new account that has not been used for crawling
2. Using a new IP node
3. Using a new runtime environment (conda env)
4. Using a new hardware device (from my personal computer to my work computer)
It is not possible to completely solve the problem.
After crawling 1-2 accounts, the above error will still occur.

**Comment by KingMaoDou** [comment]
https://github.com/vladkens/twscrape/issues/82#issue-1940124529

It seems that others have also encountered this problem.

**Comment by KingMaoDou** [comment]
![image](https://github.com/vladkens/twscrape/assets/114294557/52bc8b86-2c61-427e-86bd-96931ca8eb56)


a new error

**Comment by arbuzz202** [comment]
I've also encountered this problem, twitter API guideline says it's a problem on their side but my guess it's a shadow ban

**Comment by vladkens** [comment]
This is unknown error from Twitter. Should be fixed by PR https://github.com/vladkens/twscrape/pull/80 from v0.9
