### ISSUE TITLE
Manual entry of email verification code

### ISSUE THREAD

**Issue by vladkens** [vladkens/twscrape#9]
Make email_password optional and manually enter the verification code via the CLI command.

Login flow should continue from verification code if it provided

**Comment by KingMaoDou** [comment]
How can i manually enter the verification code via the CLI command?

**Comment by KingMaoDou** [comment]
What command can i use to manually enter the verification?

**Comment by vladkens** [comment]
Released in https://github.com/vladkens/twscrape/releases/tag/v0.10.0

**Comment by nachosnieg** [comment]
What command can i use to manually enter the verification?
