### ISSUE TITLE
Weird id for twitter user...

### ISSUE THREAD

**Issue by feesgo** [vladkens/twscrape#90]
I am using twscrape  from command line.

I get  user id with this command:

twscrape user_by_login GobiernoMX

But appears a weird id for twitter user:

{"id": 1067218403914436608, "id_str": "1067218403914436608", "url": "https://twitter.com/GobiernoMX", "username": "GobiernoMX", "displayname": "Gobierno de M\u00e9xico", "rawDescription": "Cuenta de la Presidencia del Gobierno de M\u00e9xico.", "created": "2018-11-27 00:47:50+00:00", "followersCount": 2234448, "friendsCount": 177, "statusesCount": 19601, "favouritesCount": 1338, "listedCount": 2142, "mediaCount": 10023, "location": "M\u00e9xico", "profileImageUrl": "https://pbs.twimg.com/profile_images/1675181354479153152/92DvNtnA_normal.jpg", "profileBannerUrl": "https://pbs.twimg.com/profile_banners/1067218403914436608/1695041809", "protected": null, "verified": false, "blue": true, "blueType": "Government", "descriptionLinks": [{"url": "https://www.gob.mx/presidencia", "text": "gob.mx/presidencia", "tcourl": "https://t.co/Ilp716Pi8b"}], "_type": "snscrape.modules.twitter.User"}

Then I tried  to get this user messages with this command:

twscrape user_tweets 1067218403914436608 --limit=20

But nothing appears...

Why?

Thank you in advance.

I have tried twscrape with other twitter users and I can get his messages without any trouble.

But with this user I have this trouble.

**Comment by vladkens** [comment]
I checked right now. All works fine for this user_id `twscrape user_tweets 1067218403914436608 --limit=20`. Maybe some bug on twitter side on time when you querying.
