### ISSUE TITLE
Unknown scheme for proxy URL

### ISSUE THREAD

**Issue by stachic** [vladkens/twscrape#96]
Hey! Love your lib. I am running into an issue when trying to use accounts with proxies. I am using IP authenticated proxies with no username;pass in a format of ip:port. 

I tried both:
proxy = '39.153.102.109:8800'
proxy = 'http://39.153.102.109:8800'

and always running into 'Unknown scheme for proxy URL' error. Please help!

**Comment by polyphia** [comment]
Same here, there is def sthg wrong with this

**Comment by vladkens** [comment]
@polyphia should be fixed in v0.11
