### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by xymou** [vladkens/twscrape#97]
Hi! 
Thanks for your brilliant project! I met a problem when logining in:
`2023-12-15 22:31:17.262 | ERROR    | twscrape.accounts_pool:login:141 - Error logging in to @xxx`

After debugging, I found that it stuck in get_guest_token.
Do you know how to deal with this issue?
Thank you si much!

**Comment by vladkens** [comment]
Hi, @xymou. I think it same with this issues https://github.com/vladkens/twscrape/issues/91

Most likely ip ban. Try to change ip address or retry in some sime.
