### ISSUE TITLE
How to solve this problem “No account available for queue "SearchTimeline"”

### ISSUE THREAD

**Issue by wenrenyueke** [vladkens/twscrape#99]
It takes 4 hours to wait “Next available”
2023-12-22 15:43:37.410 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:260 - No account available for queue "SearchTimeline". Next available at 17:42:48

**Comment by feliks912** [comment]
All accounts in the list are blocked by Twitter. In my experience I had to re-login manually, only to be greeted by a double captcha. After that, I could log in using twscrape.

**Comment by vladkens** [comment]
@wenrenyueke check you accounts status by

```
twscrape stats
twscrape accounts
```
